import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const qa = [
    {
      q: "qlksadfja ldfdlsfkasd;fl;sd lfk?",
      a: "ldkjflsdjflsajdlfjslkdfjlksdjflkjdlkfjlksjdflkjl flksdjflkajsdlkfjlaksdjflkas dflkjalkdsfjlkjdflkjlkjlkfjl"
    },{
      q: "qlksadfja ldfdlsfkasd;fl;sd lfk?",
      a: "ldkjflsdjflsajdlfjslkdfjlksdjflkjdlkfjlksjdflkjl flksdjflkajsdlkfjlaksdjflkas dflkjalkdsfjlkjdflkjlkjlkfjl"
    },{
      q: "qlksadfja ldfdlsfkasd;fl;sd lfk?",
      a: "ldkjflsdjflsajdlfjslkdfjlksdjflkjdlkfjlksjdflkjl flksdjflkajsdlkfjlaksdjflkas dflkjalkdsfjlkjdflkjlkjlkfjl"
    },{
      q: "qlksadfja ldfdlsfkasd;fl;sd lfk?",
      a: "ldkjflsdjflsajdlfjslkdfjlksdjflkjdlkfjlksjdflkjl flksdjflkajsdlkfjlaksdjflkas dflkjalkdsfjlkjdflkjlkjlkfjl"
    },
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Questions and Answes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to QA
        </h1>
        <br/>
        {
          qa.map((q,index)=>{
            return (
              <div key={index}>
                  <h4>{q.q}</h4>
                  <p>{q.a}</p>
              </div>
            )
            })
        }
      </main>

      <footer className={styles.footer}>
       copyrights@20922
      </footer>
    </div>
  )
}
